skills:
  - skill_name: verification-before-completion
    local_path: verification-before-completion
    repo: obra/superpowers
    ref: main
    source_path: skills/verification-before-completion
    last_synced_commit: f2cbfbefebbfef77321e4c9abc9e949826bea9d7

  - skill_name: systematic-debugging
    local_path: systematic-debugging
    repo: obra/superpowers
    ref: main
    source_path: skills/systematic-debugging
    last_synced_commit: f2cbfbefebbfef77321e4c9abc9e949826bea9d7

  - skill_name: find-skills
    local_path: .system/find-skills
    repo: vercel-labs/skills
    ref: main
    source_path: skills/find-skills
    last_synced_commit: c5ad3a85b4d16666974b161131413d08bfef3f7e

  - skill_name: skill-creator
    local_path: .system/skill-creator
    repo: openai/skills
    ref: main
    source_path: skills/.system/skill-creator
    last_synced_commit: 590b49edc158611a2b2ed715ae73f27eb70d251a

  - skill_name: skill-installer
    local_path: .system/skill-installer
    repo: openai/skills
    ref: main
    source_path: skills/.system/skill-installer
    last_synced_commit: 590b49edc158611a2b2ed715ae73f27eb70d251a

  - skill_name: vercel-composition-patterns
    local_path: vercel-composition-patterns
    repo: vercel-labs/agent-skills
    ref: main
    source_path: skills/composition-patterns
    last_synced_commit: c39c4eb8a2981b0455e033882812c9df49bb72c5

  - skill_name: vercel-react-best-practices
    local_path: vercel-react-best-practices
    repo: vercel-labs/agent-skills
    ref: main
    source_path: skills/react-best-practices
    last_synced_commit: c39c4eb8a2981b0455e033882812c9df49bb72c5

  - skill_name: web-design-guidelines
    local_path: web-design-guidelines
    repo: vercel-labs/agent-skills
    ref: main
    source_path: skills/web-design-guidelines
    last_synced_commit: c39c4eb8a2981b0455e033882812c9df49bb72c5

  - skill_name: design-dna
    local_path: design-dna
    repo: zanwei/design-dna
    ref: main
    source_path: .
    last_synced_commit: 9d9d79568df31cd846681f89fd3be1c3ce0c2aff

  - skill_name: web-shader-extractor
    local_path: web-shader-extractor
    repo: lixiaolin94/skills
    ref: main
    source_path: web-shader-extractor
    last_synced_commit: 72caac27cb0ed7446a59efb880ca09d49ca55a9e
